import numpy as np
import matplotlib.pyplot as plt
import streamlit as st
from reportlab.platypus import SimpleDocTemplate, Paragraph, Image as RLImage, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from datetime import datetime
import os

# App title
st.title("--Eco-SandWatch -- ")

# Branding assets
LOGO_PATH = "eco_sandwatch_logo.png"  # Place your logo in the same folder

# File uploader
uploaded_file = st.file_uploader("Upload your .npy DEM file", type=["npy"])

if uploaded_file:
    # Load DEM data
    dem_data = np.load(uploaded_file)

    # Display DEM
    st.subheader("Uploaded DEM Visualization")
    plt.imshow(dem_data, cmap="terrain")
    plt.colorbar(label="Elevation (m)")
    plt.title("Digital Elevation Model")
    plt.savefig("detection_result.png")  # Save for PDF
    st.pyplot(plt)

    # Simple detection logic
    threshold = np.mean(dem_data) - 5
    mining_detected = np.any(dem_data < threshold)
    detection_summary = "🚨 Mining activity detected!" if mining_detected else "✅ No mining activity detected."

    st.subheader("Detection Result")
    st.write(detection_summary)

    # Function to create PDF report
    def create_pdf_report(file_name, result_text, image_path):
        doc = SimpleDocTemplate("detection_report.pdf")
        styles = getSampleStyleSheet()
        content = []

        # Add Logo
        if os.path.exists(LOGO_PATH):
            content.append(RLImage(LOGO_PATH, width=2*inch, height=2*inch))
            content.append(Spacer(1, 12))

        # Title & Tagline
        content.append(Paragraph("Eco-SandWatch Detection Report", styles["Title"]))
        content.append(Paragraph("<i>AI-Powered Illegal Sand Mining Detection</i>", styles["Italic"]))
        content.append(Spacer(1, 12))

        # Date & file info
        content.append(Paragraph(f"📅 Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
        content.append(Paragraph(f"📂 Analyzed File: {file_name}", styles["Normal"]))
        content.append(Spacer(1, 12))

        # Result
        content.append(Paragraph(result_text, styles["Normal"]))
        content.append(Spacer(1, 12))

        # DEM visualization
        content.append(RLImage(image_path, width=5*inch, height=3.5*inch))

        # Footer note
        content.append(Spacer(1, 20))
        content.append(Paragraph("<font size=9>Generated by Eco-SandWatch Prototype – Phase 1</font>", styles["Normal"]))

        doc.build(content)

    # PDF download button
    if st.button("Generate & Download PDF Report"):
        create_pdf_report(uploaded_file.name, detection_summary, "detection_result.png")
        with open("detection_report.pdf", "rb") as pdf_file:
            st.download_button(
                label="📄 Download Eco-SandWatch Report",
                data=pdf_file,
                file_name="Eco-SandWatch_Report.pdf",
                mime="application/pdf"
            )